### ISSUE TITLE
alignment of add services page contents

### ISSUE THREAD

**Issue by JarrodWil** [JarrodWil/Salesforce-Feb-2022-Release#10]
want to make sure that all our items align to centre line of text boxes please

Current
![image](https://user-images.githubusercontent.com/93557524/155264945-4f8c78d8-f43a-4931-94fa-b20afa07ba76.png)

Requested - Front
![image](https://user-images.githubusercontent.com/93557524/155265068-ea7c014b-6717-4b9e-a192-8ba7d30a9168.png)

Requested - End
![image](https://user-images.githubusercontent.com/93557524/155265112-d6fe19e3-8314-4dd6-97eb-07daf920112b.png)

**Comment by herbgdestined** [comment]
hi @JarrodWil please see updated alignment and let me know if all good

![image](https://user-images.githubusercontent.com/100175500/155284094-018542b5-e36f-4333-9dfb-89e37c24d85d.png)

**Comment by JarrodWil** [comment]
Not quite

![image](https://user-images.githubusercontent.com/93557524/155289750-14b1ab7c-4354-45b4-812c-634352f8bef7.png)

**Comment by JarrodWil** [comment]
For the blind homies

![image](https://user-images.githubusercontent.com/93557524/155289847-7b03955f-dd3c-42a2-a286-67f3b7da1f96.png)

![image](https://user-images.githubusercontent.com/93557524/155289922-574db76c-c857-4001-9035-620d97f324f2.png)

**Comment by herbgdestined** [comment]
Hi @JarrodWil unfortunately we cannot adjust it anymore for those checkboxes and icons.

**Comment by JarrodWil** [comment]
@herbgdestined that will haunt @jxhba every time she looks at... haha. Ok, leave as is please. Issue closed
