### ISSUE TITLE
Lead: Mandatory Brand for "Hotel (full)" project type

### ISSUE THREAD

**Issue by JarrodWil** [JarrodWil/Salesforce-Feb-2022-Release#11]
@jxhba identified that in PRD Lead Object we currently dont have mandatory brand for the above.

Is there any issue with amending this config item in PRD and TEST?

If there is, then we will leave this issue open pending go live as a reminder to amend.

**Comment by jxhba** [comment]
I've updated validation rule in Sandbox and Production now @JarrodWil 

do confirm before closing this.

**Comment by JarrodWil** [comment]
verified in Test and closed.
