### ISSUE TITLE
Remove service not working when service selected

### ISSUE THREAD

**Issue by JarrodWil** [JarrodWil/Salesforce-Feb-2022-Release#12]
Tried to change a procurement goods service (currently listed under "Other") to "Procurement (Goods)" service.

Added service and saved. Then wanted to delete the "Other" service and got below message (noting that service was selected.
https://hbacrm--cidev.lightning.force.com/lightning/cmp/c__ServiceProposalLightningApp?c__recordId=0062r000004Ic6oAAC&c__pageType=edit

![image](https://user-images.githubusercontent.com/93557524/155266966-b45fde5c-cc13-4224-8556-c2936c23fb8a.png)

**Comment by JarrodWil** [comment]
Then went back in and it was deleted as below

![image](https://user-images.githubusercontent.com/93557524/155267553-499885cb-af2e-437d-ae6d-3ba3c1dd9cd3.png)

**Comment by JarrodWil** [comment]
Here are some other examples of those proposals if it helps

![image](https://user-images.githubusercontent.com/93557524/155268524-3179808c-fc38-4097-aabd-94548ec11d5c.png)

**Comment by herbgdestined** [comment]
Hi @JarrodWil this has been fixed and retested on our end.

Kindly check again on your end.

**Comment by JarrodWil** [comment]
verified and closed. thanks
