### ISSUE TITLE
Rename Service "Other" to "Others"

### ISSUE THREAD

**Issue by jxhba** [JarrodWil/Salesforce-Feb-2022-Release#13]
Highlighting this in case we need to Patch data instead of just renaming

![image](https://user-images.githubusercontent.com/100175811/155272381-f8617134-5269-493d-b38b-18ea07a0b8b8.png)

**Comment by herbgdestined** [comment]
Hi @jxhba please see update and confirm

![image](https://user-images.githubusercontent.com/100175500/155283960-3df36a5f-a7af-4c6e-9c8d-65e2df0662df.png)

**Comment by jxhba** [comment]
Looks ok to me now. Will wait for @JarrodWil to confirm

**Comment by JarrodWil** [comment]
Happy and ok as long as @jxhba is happy with this one. JX, you could have closed since you opened the issue.
