### ISSUE TITLE
Edit Service Tab Column

### ISSUE THREAD

**Issue by jxhba** [JarrodWil/Salesforce-Feb-2022-Release#14]
Hi @herbgdestined, with the new Services Names, can we edit this column to show Design Office?

![image](https://user-images.githubusercontent.com/100175811/155295601-eb2c1d23-62bd-40aa-a1b2-1051fcefa23a.png)

**Comment by herbgdestined** [comment]
Hi @JarrodWil let me know if like this is ok

![image](https://user-images.githubusercontent.com/100175500/155298632-0524c0cd-7ae9-42a9-9d97-cb07a1f75a8f.png)

**Comment by JarrodWil** [comment]
a good change. good suggestion @jxhba. 

@herbgdestined Please deploy and close comment when read

**Comment by herbgdestined** [comment]
Above is already done in Sandbox.
