### ISSUE TITLE
Service "Original Amount" not showing figure

### ISSUE THREAD

**Issue by jxhba** [JarrodWil/Salesforce-Feb-2022-Release#15]
Hi @herbgdestined

Edited a fee:
![image](https://user-images.githubusercontent.com/100175811/155297958-44bd51e8-ffe6-4e87-bc23-4d04dc63da07.png)

But not reflected in Add/Edit Service page:
![image](https://user-images.githubusercontent.com/100175811/155298035-bc8e70ca-c1db-4e30-91f2-8700615261cb.png)

**Comment by herbgdestined** [comment]
hi @jxhba how did you encounter this? I can't seem to replicate it using same record and adding new services and updating the value

![image](https://user-images.githubusercontent.com/100175500/155299079-482222d8-18f9-4128-9cb5-4818bea2c02d.png)

**Comment by jxhba** [comment]
i was testing it as per usual flow. now it seems fine again.
i was testing on this:
https://hbacrm--cidev.lightning.force.com/lightning/r/Opportunity/0061m00000550ZFAAY/view

Will try again tmr on a new proposal

**Comment by herbgdestined** [comment]
Noted @jxhba let us know if ever

**Comment by jxhba** [comment]
this is ok now. thanks!
