### ISSUE TITLE
Management Fee showstopper: User unable to save after changes after applying Mgt Fee

### ISSUE THREAD

**Issue by JarrodWil** [JarrodWil/Salesforce-Feb-2022-Release#16]
Was doing a screen resolution test with Binu (he is on a 13 inch Macbook). He tried the management fee calculator and get the below error when trying to save. All users should be able to apply management fees to their records.

@jxhba have you been doing your testing under Admin account (i have and perhaps this is a gap in our testing).

Project Record:
![image](https://user-images.githubusercontent.com/93557524/155444776-ac9fa772-bc0b-4f2d-976b-38c9a173c829.png)

error message
![image](https://user-images.githubusercontent.com/93557524/155444704-d331fa54-25fe-4a4b-b931-0805ee35cecd.png)

**Comment by herbgdestined** [comment]
Hi @JarrodWil they are editing a record that they do not own I believe.

Please use a record that they have edit access.

**Comment by JarrodWil** [comment]
good thinking. need second coffee. let me try using admin - logging in as another user

**Comment by JarrodWil** [comment]
confirming that sky is not falling (will put my chicken little away for a while).

Tested on a Binu record and worked fine. Apologies. Issue closed.
