### ISSUE TITLE
Co-Ordination: business rule when moving to a "co-ord" service to a new proposal

### ISSUE THREAD

**Issue by JarrodWil** [JarrodWil/Salesforce-Feb-2022-Release#17]
Hi Herbert,

Can you advise the business rule for a proposal that has 2 services: 1) primary service and 2) other service with co-ord deducted at 10%?

Interested to know impact of original proposal and value shifted to new proposal.

Thanks

**Comment by herbgdestined** [comment]
Hi @JarrodWil - If Co-ord is selected, the non primary services Net Fee will be reduced based on the Co-ord % per service line. That deducted amount would be added to the Net Fee of the Primary Service line.

Once saved, the Total Fee should still be the same but the Primary Service Net Fee will be his current fee + the total Co-ord amount.

**Comment by JarrodWil** [comment]
so recommended business rule would be when transferring a service to another proposal where co-ord has been applied to source proposal
1. change co-ord for trfring svc to 0%
2. tfr to new proposal

**Comment by jxhba** [comment]
riding from the same issue title, i was testing on a new proposal that was created from Add/Edit Service Pop up > select row > "Create Proposal"
here's the new proposal created:
https://hbacrm--cidev.lightning.force.com/lightning/r/Opportunity/0061m00000556BTAAY/view

should the logic be not defaulting any Co-ord here?: @herbgdestined 
![image](https://user-images.githubusercontent.com/100175811/156291115-829ba6b2-cd0a-4af8-8659-35da7129d3f2.png)

@JarrodWil was this the same thing u were highlighting?

**Comment by herbgdestined** [comment]
hi @JarrodWil @jxhba apologies, you may have been testing while they are fixing.

This is ok now, kindly check again and let me know.

**Comment by JarrodWil** [comment]
hi @herbgdestined tested and works as expected. Situation with transfer of service to another proposal is a fringe case, so we will communicate to set co-ord to 0% prior to close/ lost or transferring a service to another proposal.

hi @jxhba over to you if you are ok with this to close this issue.
