### ISSUE TITLE
Service values not updating on save

### ISSUE THREAD

**Issue by JarrodWil** [JarrodWil/Salesforce-Feb-2022-Release#18]
Test Steps
1. Do a proposal with a Co-Ord service
2. Do a new proposal off same lead with 4 services ($100 per service), save after adding services
3. Went back into services and co-ord has been deducted (though no co-ord applied)
4. Changed services back to original values and saved
5. Went back into services and values still showing as co-ord deducted

Values altered before saving
![image](https://user-images.githubusercontent.com/93557524/156093949-44c2d3d4-fc8b-45f4-8f0b-1ef3b2f00abd.png)

After save and going back into services
![image](https://user-images.githubusercontent.com/93557524/156093888-34bc4dbb-4a68-42e0-9bf8-ba213619ae42.png)

Summary
![image](https://user-images.githubusercontent.com/93557524/156094031-629000cf-136d-4ab0-9f47-a0bc165f70ac.png)

**Comment by JarrodWil** [comment]
This was the proposal
https://hbacrm--cidev.lightning.force.com/lightning/r/Opportunity/0061m00000555ggAAA/view

@jxhba FYI

**Comment by herbgdestined** [comment]
Hi @JarrodWil apologies I have been trying for a few records on this and really could not replicate it.

I can jump into a call with you for this. But can I ask you to try a new record and replicate this again and provide me the steps?

**Comment by JarrodWil** [comment]
Let me try and replicate my end.

**Comment by JarrodWil** [comment]
ok, lets do a call

**Comment by JarrodWil** [comment]
new proposal created in same browser window. all services set to $100. Saved. When reenter, is auto allocating co-ord at 10%

![image](https://user-images.githubusercontent.com/93557524/156103983-3ea05dab-986c-4bdb-b332-cefc0d1e46f5.png)

https://hbacrm--cidev.lightning.force.com/lightning/r/Opportunity/0061m00000555kiAAA/view

**Comment by herbgdestined** [comment]
Hi @JarrodWil please test this again.

This issue should be ok now. Let me know if all good or any issue.

**Comment by JarrodWil** [comment]
@herbgdestined I am saving on exit of Services screen and getting mixed results about saved activity being retained.

https://hbacrm--cidev.lightning.force.com/lightning/r/Opportunity/0061m00000555xIAAQ/view

https://hbams-my.sharepoint.com/:v:/g/personal/jarrod_williams_hba_com/EQvWyK7ORGtAo7hUsZmLRPoBm_5YfQvqkvuVFnVcTB5BAQ?e=2Nbjg5

**Comment by JarrodWil** [comment]
Go into Add/Edit Services
![image](https://user-images.githubusercontent.com/93557524/156122196-806dc1b5-1a9e-4626-be2f-75699fc27da2.png)

Then summary screen showing
![image](https://user-images.githubusercontent.com/93557524/156122247-1a7e08cc-57b6-4bbc-8849-5895bf9c4a0e.png)

**Comment by herbgdestined** [comment]
Hi @JarrodWil please test again, the bug has been fixed on saving the net fee to sales price.

**Comment by JarrodWil** [comment]
Hi @herbgdestined tested and working as expected:
1. new prop created, services selected, saved, co-ord applied. --> inspected as before saved
2. back into services, select co-ord, saved --> inspected as before saved
3. new prop created, services selected, saved --> inspected & no co-ord auto applied
4. back into services, select co-ord, changed 1 to 0%, saved --> inspected as before saved
5. back into services, select co-ord to 0% for all co-ord services, saved --> inspected as before saved :) like that co-ord removes in total.

Hi @jxhba if your testing same, then please close this issue
