### ISSUE TITLE
Edit Co-od dropdown

### ISSUE THREAD

**Issue by jxhba** [JarrodWil/Salesforce-Feb-2022-Release#19]
Hi @herbgdestined ,

Please add the % to the dropdown:
A (5%)
B (10%)
C (15%)

![image](https://user-images.githubusercontent.com/100175811/156119590-a4ed2994-01dd-4abc-85ba-8279a3b7ffd1.png)

**Comment by herbgdestined** [comment]
Hi @jxhba updated, please see change
![image](https://user-images.githubusercontent.com/100175500/156120644-c05b7ead-d42c-449b-acd4-8e2ce7231ae0.png)

**Comment by JarrodWil** [comment]
@herbgdestined  can we have a space please between A & (5%)

**Comment by herbgdestined** [comment]
Hi @JarrodWil updated this to below
![image](https://user-images.githubusercontent.com/100175500/156121950-f179308b-084e-4e48-a219-d67348f741b5.png)

**Comment by JarrodWil** [comment]
Thanks

@jxhba Ok to close if you are happy

**Comment by jxhba** [comment]
yes looks good now. thank you @herbgdestined
