### ISSUE TITLE
Management Fee: Max % not set; Able to also set Negative value.

### ISSUE THREAD

**Issue by JarrodWil** [JarrodWil/Salesforce-Feb-2022-Release#2]
Thought we discussed a max value here. I was able to add 99%. Please set to max value of 50% and Min value of 0%

https://hbacrm--cidev.lightning.force.com/lightning/r/Opportunity/0061m0000054zHUAAY/view

![image](https://user-images.githubusercontent.com/93557524/155089640-e571b3ef-2175-4973-a9ad-db780b421ff0.png)

![image](https://user-images.githubusercontent.com/93557524/155089793-c2e01162-2981-4173-b59b-c72c059fddde.png)

**Comment by JarrodWil** [comment]
Can also set a negative %age value
https://hbacrm--cidev.lightning.force.com/lightning/r/Opportunity/0062r000005S11tAAC/view

![image](https://user-images.githubusercontent.com/93557524/155095874-4eae60c8-a0fd-4d0e-87f3-2a7f21b80cad.png)

**Comment by herbgdestined** [comment]
Hi @JarrodWil this is ok now you should see this validation
![image](https://user-images.githubusercontent.com/100175500/155246741-dfc1b538-45f0-42ae-83de-6c6e4f562ead.png)

**Comment by JarrodWil** [comment]
Verified and closed.
