### ISSUE TITLE
Net Fee computation

### ISSUE THREAD

**Issue by jxhba** [JarrodWil/Salesforce-Feb-2022-Release#21]
Testing around this Proposal Item:
https://hbacrm--cidev.lightning.force.com/lightning/r/Opportunity/0061m00000555lvAAA/view

1) Changed one line of service (Archi with A(5%) co-ord) to "Lost", but Net Fee was still summing it all. **(ISSUE 1)**
2) So then I try changed that line of co-ord to "None", record saved but after that it became "B (10%)". **(ISSUE 2)**
3) Which now the Fee on Proposal Page is also not matching the services lines: **(ISSUE 3)**
![image](https://user-images.githubusercontent.com/100175811/156147743-c450e0a3-ee06-43be-a785-5a9493d16e16.png)

![image](https://user-images.githubusercontent.com/100175811/156148090-e329a4e1-5eaf-4822-9ef6-92349b92400b.png)

@herbgdestined

**Comment by herbgdestined** [comment]
Hi @jxhba what was the original setup for a service line that is Lost? It is removed from Total Fee?

**Comment by JarrodWil** [comment]
hi Herbert, yes when a service was lost, it was removed from the proposal including the fee for that service.
________________________________

**Comment by herbgdestined** [comment]
Hi @JarrodWil is the Fee just set to 0? Apologies as I cannot see current behaviour in Production once it is set to Lost on the service line.

**Comment by JarrodWil** [comment]
Yes, service current remains in the proposal and the fee shows as $0 (however marked as lost in the reporting).
________________________________
From: herbgdestined ***@***.***>
Sent: Tuesday, March 1, 2022 8:20 PM
To: JarrodWil/Salesforce-Feb-2022-Release ***@***.***>
Cc: Jarrod Williams ***@***.***>; Mention ***@***.***>
Subject: Spam: Re: [JarrodWil/Salesforce-Feb-2022-Release] Net Fee computation (Issue #21)


Hi @JarrodWil<https://github.com/JarrodWil> is the Fee just set to 0? Apologies as I cannot see current behaviour in Production once it is set to Lost on the service line.

**Comment by herbgdestined** [comment]
Thanks @JarrodWil and @jxhba this should be ok now.

Kindly retest and let us know.

**Comment by jxhba** [comment]
Fee still dont look right:
Testing on https://hbacrm--cidev.lightning.force.com/lightning/r/Opportunity/0061m00000556qBAAQ/view

In Proposal Page:
![image](https://user-images.githubusercontent.com/100175811/156287626-4d959910-3212-46ad-add8-48efc0ff4094.png)

In Service Pop up:
![image](https://user-images.githubusercontent.com/100175811/156287645-9dac9aa7-84b0-441f-b162-d0dbe51d811c.png)

@herbgdestined
