### ISSUE TITLE
Previous Fee

### ISSUE THREAD

**Issue by jxhba** [JarrodWil/Salesforce-Feb-2022-Release#22]
Hi @herbgdestined 

created new proposal from Service Page. the line of service was marked lost > Select line > Create Proposal
in the new created proposal here:
https://hbacrm--cidev.lightning.force.com/lightning/r/Opportunity/0061m00000559CcAAI/view

I change the inherited line of service = "Included in Proposal"
then added a new service with $100 > saved
then edited the 2nd service fee to be $200 > saved

the "Previous Fee" on Proposal page dont seems logical:
Should be $7100 but it's just $100
![image](https://user-images.githubusercontent.com/100175811/156502023-51a474ef-c72b-45cd-b422-5d8e45903280.png)

Seems to be taking just the "Previous Fee" column:
![image](https://user-images.githubusercontent.com/100175811/156502126-0ec0eb80-fba1-4046-a8bf-243bb3908793.png)

cc @JarrodWil

**Comment by herbgdestined** [comment]
Hi @jxhba I believe this is a current setup that we did not touch.

I think the current setup is that once it is copied from an existing line it treats it as a new value. Since you did not update the 7000 Line then it treats that value as the current value and it has no previous fee.
