### ISSUE TITLE
"Lost" Service > Create New Proposal

### ISSUE THREAD

**Issue by jxhba** [JarrodWil/Salesforce-Feb-2022-Release#23]
@herbgdestined 
logic in production will reflag the inherit "Lost" line to "Included in Proposal" in the new created Proposal
but now in Sandbox, it's still = "Lost"

in production:
![image](https://user-images.githubusercontent.com/100175811/156504745-2a6965de-3546-4d33-9c2d-df843a6d3b39.png)
https://hbacrm.lightning.force.com/lightning/r/Opportunity/00684000001rqJ8AAI/view

in sandbox:
![image](https://user-images.githubusercontent.com/100175811/156504816-b1a300c7-3609-4b5a-b728-46f978bd1e02.png)
https://hbacrm--cidev.lightning.force.com/lightning/cmp/c__ServiceProposalLightningApp?c__recordId=0061m00000559F7AAI&c__pageType=edit

cc @JarrodWil

**Comment by herbgdestined** [comment]
Hi @jxhba this has been updated to be the same as production. Kindly retest and let me know.

**Comment by jxhba** [comment]
ok now. thanks! @herbgdestined
