### ISSUE TITLE
Reporting Field - Original Sale price

### ISSUE THREAD

**Issue by JarrodWil** [JarrodWil/Salesforce-Feb-2022-Release#24]
Hi Herbert, can you advise the name of field 

My check shows that "Net Fee $" is showing in "Sales Price"

Can you advise what mapping will be in place for "Fee $" as I expect we may want to report on this?

IE what will be field name of "Fee $" for reporting purposes.

@jxhba FYI

![image](https://user-images.githubusercontent.com/93557524/156521829-ecbef4f0-7f30-447c-a19f-39449de05144.png)

**Comment by herbgdestined** [comment]
Hi @JarrodWil it is on the Current Fee field

![image](https://user-images.githubusercontent.com/100175500/156523023-2d052acb-3b7c-4e2a-be4e-2e601a652f38.png)

**Comment by JarrodWil** [comment]
Excellent. Thank you. Confirmed as below:

![image](https://user-images.githubusercontent.com/93557524/156524488-99b04dc4-072a-4da7-ab1d-179e9ba1a9a8.png)
