### ISSUE TITLE
Clone graphic: Same size as other graphics

### ISSUE THREAD

**Issue by JarrodWil** [JarrodWil/Salesforce-Feb-2022-Release#3]
Please make the clone icon same size as contact icons.

![image](https://user-images.githubusercontent.com/93557524/155091863-8c48af77-d417-408b-a634-71aa302ecc27.png)

**Comment by herbgdestined** [comment]
Hi @JarrodWil this is ok now, it should look like this

![image](https://user-images.githubusercontent.com/100175500/155246813-5ed0e420-e513-4510-9ddd-b1d8679984c6.png)

**Comment by JarrodWil** [comment]
Reviewed and agree. Closed
