### ISSUE TITLE
Service Select: move to last field please

### ISSUE THREAD

**Issue by JarrodWil** [JarrodWil/Salesforce-Feb-2022-Release#4]
please move to end as last field

![image](https://user-images.githubusercontent.com/93557524/155092199-7de5a5e5-273d-45e3-b2fa-5dbc5f594ae5.png)

**Comment by herbgdestined** [comment]
Hi @JarrodWil  we have moved this, I think it is better if it is before the clone icon.

![image](https://user-images.githubusercontent.com/100175500/155246886-350f9171-5f43-4f08-bbab-24edb008d786.png)

**Comment by JarrodWil** [comment]
Verified and aree. Issue closed.
