### ISSUE TITLE
Proposal Summary Screen: Management Fee

### ISSUE THREAD

**Issue by JarrodWil** [JarrodWil/Salesforce-Feb-2022-Release#5]
Was this going to be hidden? If so, please remove.

![image](https://user-images.githubusercontent.com/93557524/155092590-800a6881-d1bb-439e-86d3-5d7df11c3a3d.png)

**Comment by herbgdestined** [comment]
Hi @JarrodWil  apologies, field has been removed

![image](https://user-images.githubusercontent.com/100175500/155246959-5d160e6c-22cd-4cda-bafd-593d10cde083.png)

**Comment by JarrodWil** [comment]
verified and closed
