### ISSUE TITLE
Services Clone: Roll over text

### ISSUE THREAD

**Issue by JarrodWil** [JarrodWil/Salesforce-Feb-2022-Release#7]
Seeking roll over guidance test. Tried this, however no message displayed. Tried to get screen grab, however mouse location doesnt show on screen grab.

**Comment by herbgdestined** [comment]
Hi @JarrodWil can I get more context on this item.

**Comment by JarrodWil** [comment]
@herbgdestined like this

![image](https://user-images.githubusercontent.com/93557524/155104937-23433c35-9135-47dc-ac1e-5700518f0685.png)

**Comment by herbgdestined** [comment]
@JarrodWil a hover text field on the clone icon right? Let me check with the team.

**Comment by JarrodWil** [comment]
Yes please

**Comment by herbgdestined** [comment]
Hi @JarrodWil we have added this hover text below
![image](https://user-images.githubusercontent.com/100175500/155247095-17f716c5-82c2-46d9-a09f-9421d3688232.png)

**Comment by JarrodWil** [comment]
verified and closed.
