### ISSUE TITLE
Service pop-up page Rename Column and Realignment

### ISSUE THREAD

**Issue by jxhba** [JarrodWil/Salesforce-Feb-2022-Release#9]
please see screenshot:
![image](https://user-images.githubusercontent.com/100175811/155258320-fb6abaea-d2c4-4a70-8a43-e2311541035e.png)

(updated screenshot)

**Comment by herbgdestined** [comment]
Hi @jxhba please see updated labels and total alignment

![image](https://user-images.githubusercontent.com/100175500/155284335-9c2e760d-53db-4659-824e-a0ae0bfc16c8.png)

**Comment by jxhba** [comment]
Hi @herbgdestined thanks but the alignment and 2 titles need amend please (circled yellow):
Align the bottom "Total" to right of the column of "Service" column.
Then the Total Figures to shift right a bit, to follow those Figures in boxes above.

![image](https://user-images.githubusercontent.com/100175811/155286591-94da4401-848c-4031-b69c-2250da1e69a2.png)

**Comment by herbgdestined** [comment]
Hi @jxhba let me know if below is better.

![image](https://user-images.githubusercontent.com/100175500/155289496-7e0d9d3d-2042-47b4-aceb-606da3514b70.png)

**Comment by jxhba** [comment]
@herbgdestined align the numbers
![image](https://user-images.githubusercontent.com/100175811/155290919-ea120761-7203-44f5-a8b2-b5a76b81b7f6.png)

**Comment by herbgdestined** [comment]
Hi @jxhba I checked with the team and we can only align like this, kindly check if all ok

![image](https://user-images.githubusercontent.com/100175500/155297760-66001762-b078-4a7c-a193-634cb24f4e2e.png)

**Comment by jxhba** [comment]
@JarrodWil to confirm if you're ok.
and is it ok for "Management Fee $" column to be smaller? @herbgdestined

**Comment by herbgdestined** [comment]
It can be smaller if we rename that column to something like "Mgnt Fee $" @jxhba

**Comment by JarrodWil** [comment]
@herbgdestined I am ok with suggestion as left side of screen is premium real estate.

**Comment by jxhba** [comment]
ok with "Mgmt Fee $"

**Comment by jxhba** [comment]
@herbgdestined can we adjust this column name to "Previous Fee $"
to align with other Fee $ column, and also the new Proposal-Service Tab columns:

![image](https://user-images.githubusercontent.com/100175811/155445173-0c5b9ec8-8a90-4825-862d-c865b9adff38.png)

**Comment by herbgdestined** [comment]
Hi @jxhba please see changes done
![image](https://user-images.githubusercontent.com/100175500/155451671-7f9abb44-955f-4c4a-9499-ef14e2d5ef22.png)
